def kartta ():
    kartta = (f"\nBIKF XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX ENTC  "
              f"\n X  X                                X  X   "
              f"\n  X   X                           EFKT   X   "
              f"\n  X    X                         X       X   "
              f"\n  X     X        ENGM XXXXXX EFHK        X   "
              f"\n  X      X      X    X      X            X   "
              f"\n  X       X    X      X    X             X   "
              f"\n  X        EGPD        ESSA              X   "
              f"\n  X                   X                  X   "
              f"\n  X                  X                   X   "
              f"\n  X                 X                    X   "
              f"\n  X             EKBI                    EVRA "
              f"\n  X            X    X                    X   "
              f"\n  X           X      X                   X   "
              f"\nEGLL XXXX EHAM        EDBB XXXXXXXXXXXX EPWA "
              f"\n  X        X         X                     X "
              f"\n   X      X         X                      X "
              f"\n    X    X         X                       X "
              f"\n     LFPG       LSZH XXXXXXXXXXXXX LOWW    X "
              f"\n      X          X                X    X   X "
              f"\n      X          X               X       X X "
              f"\n      X    XXXXX LIRF XXX     LQSA XXXXX LRBS"
              f"\n      X  X               X    X              "
              f"\n     LEMD                 LGAV               "
              f"\n         X               X                   "
              f"\n          XXXXXXXXXXXXXXX                    "
              ).replace("X", "-")
    print(kartta)
    return
